<section class="login-section">
    <h2 class="login-title">Connexion</h2>
    
    <form class="login-form" method="post">
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" required>
        
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
        
        <button type="submit">Se connecter</button>
    </form>
    <?php if (isset($_SESSION['login_error'])): ?>
        <div class="error"><?= $_SESSION['login_error'] ?></div>
        <?php unset($_SESSION['login_error']); ?> <!-- Supprimer l'erreur après l'affichage -->
    <?php endif; ?>
    
</section>
