<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Not Found - 404</title>
    <link rel="stylesheet" href="src/assets/scss/app.css">
</head>
<body>

    <div class="container404">
        <div>
            <p class="error-message">404</p>
            <p class="error-description">Oups ! La page que vous recherchez n'existe pas.</p>
            <a href="index.php" class="error-button">Retour à l'accueil</a>
        </div>
    </div>

</body>
</html>
